@ECHO OFF
SET LOGFILE=Make.log
VER >%LOGFILE%

IF EXIST TEST.EXE DEL TEST.EXE

FOR %%A IN (*.BAS) DO PBC.EXE -FNPX -G386 -ODV -OZF+ -CE -ES -EB -LB -LG %%A>>%LOGFILE%

ECHO [Info] Compilation Log:
TYPE %LOGFILE%

IF EXIST TEST.EXE ECHO [Info] Built TEST.EXE
