#!/usr/bin/env python3
# =============================================================================
# gen-vesaopt.py - expand VESAOPT.TEMPLATE.BAS into the per-width VESA families
# =============================================================================
# One source of truth (the template) instead of six hand-maintained copies.
# For every configured (width x height) mode this emits VOPT<width>.SUB with:
#   - the y*width offset auto-decomposed into a SHIFT LEFT/ADD chain from the
#     width's set bits (1600 -> y<<10 + y<<9 + y<<6; no MUL on the hot path)
#   - bank-free fill variants auto-selected where width*height <= 65536 (the
#     whole frame fits one 64k bank, i.e. mode 13h)
#   - a per-width FillCircle span table sized to the mode (height \ 2)
# plus VESAOPT.SUB (Svga_WireVesaOptimized wiring every family into
# SVGADispatch - the init hook called from Svga_InitDispatchTable's VESA case)
# and VESAOPT.INC (the aggregate the umbrella SVGA.SUB includes).
#
# Usage:  gen-vesaopt.py [--check] [WxH ...]
#   no args : regenerate all outputs in the repo root with the default modes
#   --check : regenerate in memory and fail (exit 1) if any committed output
#             drifts from the template (CI guard)
# =============================================================================
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE = os.path.join(ROOT, 'VESAOPT.TEMPLATE.BAS')

DEFAULT_MODES = [(320, 200), (640, 480), (800, 600), (1024, 768), (1280, 1024), (1600, 1200)]

GEN_NOTE = ("' GENERATED by scripts/gen-vesaopt.py from VESAOPT.TEMPLATE.BAS - DO NOT EDIT.\r\n"
            "' Change the template (or the mode list in the tool) and regenerate instead.\r\n")


def offset_chain(var, width, indent):
    # decompose y*width into shifts of the width's set bits (MSB first)
    bits = [b for b in range(15, -1, -1) if width & (1 << b)]
    lines = ['%st = %s : SHIFT LEFT t, %d : o = t' % (indent, var, bits[0])]
    for b in bits[1:]:
        lines.append('%st = %s : SHIFT LEFT t, %d : o = o + t' % (indent, var, b))
    return lines


def shift_divisions(lines, width):
    # a 386 divides a LONG in dozens of cycles but shifts in a few: turn the
    # hot /65536 bank splits (every width) and /width row math (power-of-two
    # widths only) into SHIFT RIGHT
    out = []
    wbits = (width & (width - 1)) == 0
    k = width.bit_length() - 1
    for line in lines:
        m = re.match(r'^(\s*)(\w+) = (\w+) \\ 65536$', line)
        if m:
            i, dst, src = m.groups()
            out.append('%st = %s : SHIFT RIGHT t, 16 : %s = t' % (i, src, dst))
            continue
        if wbits:
            m = re.match(r'^(\s*)(\w+) = \(([^()]+)\) \\ %d( \+ 1)?$' % width, line)
            if m:
                i, dst, expr, plus1 = m.groups()
                rep = '%s%s = %s : SHIFT RIGHT %s, %d' % (i, dst, expr, dst, k)
                if plus1:
                    rep += ' : %s = %s + 1' % (dst, dst)
                out.append(rep)
                continue
        out.append(line)
    return out


def expand_family(template_lines, width, height):
    single = (width * height) <= 65536
    out, mode, depth = [], 'keep', 0
    for raw in template_lines:
        s = raw.strip()
        if s == "' {IF:SINGLEBANK}":
            mode = 'keep' if single else 'skip'
            continue
        if s == "' {ELSE}":
            mode = 'skip' if single else 'keep'
            continue
        if s == "' {ENDIF}":
            mode = 'keep'
            continue
        if mode == 'skip':
            continue
        m = re.match(r'^(\s*)\{OFFSET:(\w+)\}\s*$', raw)
        if m:
            out.extend(offset_chain(m.group(2), width, m.group(1)))
            continue
        line = (raw.replace('{W}', str(width))
                   .replace('{SPANS}', 'V%dSpans' % width)
                   .replace('{MAXR}', str(height // 2)))
        out.append(line)
    return shift_divisions(out, width)


def family_source(width, height):
    text = open(TEMPLATE, 'rb').read().decode('latin1').replace('\r\n', '\n')
    lines = text.split('\n')
    # the family body starts at the dashed comment right before the
    # "{W}-wide VESA" header; everything above is template documentation
    start = next(i for i, l in enumerate(lines) if '{W}-wide VESA' in l) - 1
    body = expand_family(lines[start:], width, height)
    hdr = ("' =============================================================================\n"
           "' VOPT%d.SUB - %dx%d VESA 256-colour fast-path family\n"
           "' =============================================================================\n" % (width, width, height)
           + GEN_NOTE.replace('\r\n', '\n'))
    return (hdr + '\n'.join(body).rstrip('\n') + '\n').replace('\n', '\r\n')


SLOTS = ['PutPixel', 'GetPixel', 'HLine', 'VLine', 'FillRect', 'DrawRect', 'FillCircle']


def wiring_source(modes):
    out = ["' =============================================================================",
           "' VESAOPT.SUB - dispatch wiring for the per-width VESA fast paths",
           "' =============================================================================",
           GEN_NOTE.replace('\r\n', '\n').rstrip('\n'),
           '',
           "' wire the matching width family into SVGADispatch (from the VESA case)",
           'SUB Svga_WireVesaOptimized',
           '    SELECT CASE SVGAScreenContext.XRes']
    for w, _h in modes:
        out.append('        CASE %d' % w)
        for slot in SLOTS:
            out.append('            SVGADispatch.%s = CODEPTR32(Vesa%d_%s)' % (slot, w, slot))
    out += ['    END SELECT', 'END SUB', '']
    return '\n'.join(out).replace('\n', '\r\n')


def include_source(modes):
    out = ["' =============================================================================",
           "' VESAOPT.INC - aggregate of the per-width VESA fast-path families",
           "' =============================================================================",
           GEN_NOTE.replace('\r\n', '\n').rstrip('\n'),
           "' Pulled in by the umbrella SVGA.SUB; the wiring module at the end exposes",
           "' Svga_WireVesaOptimized for Svga_InitDispatchTable's VESA branch."]
    for w, _h in modes:
        out.append('$INCLUDE "VOPT%d.SUB"' % w)
    out += ['$INCLUDE "VESAOPT.SUB"', '']
    return '\n'.join(out).replace('\n', '\r\n')


def generate(modes):
    files = {('VOPT%d.SUB' % w): family_source(w, h) for w, h in modes}
    files['VESAOPT.SUB'] = wiring_source(modes)
    files['VESAOPT.INC'] = include_source(modes)
    return files


def main():
    args = sys.argv[1:]
    check = '--check' in args
    args = [a for a in args if a != '--check']
    modes = [tuple(int(p) for p in a.lower().split('x')) for a in args] or DEFAULT_MODES

    files = generate(modes)
    if check:
        drift = []
        for name, content in files.items():
            path = os.path.join(ROOT, name)
            on_disk = open(path, 'rb').read().decode('latin1') if os.path.exists(path) else None
            if on_disk != content:
                drift.append(name)
        if drift:
            print('::error::generated VESA fast-path files drift from the template: %s '
                  '- run scripts/gen-vesaopt.py and commit.' % ', '.join(drift))
            sys.exit(1)
        print('vesaopt outputs match the template (%d files).' % len(files))
        return
    for name, content in files.items():
        open(os.path.join(ROOT, name), 'wb').write(content.encode('latin1'))
        print('wrote %s (%d lines)' % (name, content.count('\r\n')))


if __name__ == '__main__':
    main()
